class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'm'
        self.UnzipMirrorCommand = 'unz'
        self.TarMirrorCommand = 'tarm'
        self.ZipMirrorCommand = 'zipm'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'lt'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clonedrive'
        self.CountCommand = 'countdrive'
        self.WatchCommand = 'wh'
        self.TarWatchCommand = 'tarwh'
        self.ZipWatchCommand = 'zipwh'
        self.QbMirrorCommand = 'qbm'
        self.QbUnzipMirrorCommand = 'qbunzipm'
        self.QbTarMirrorCommand = 'qbtarm'
        self.QbZipMirrorCommand = 'qbzip'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
